# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/marvel/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/marvel/proprietary/lib/libcamera.so:/obj/lib/libcamera.so 

# Binaries
PRODUCT_COPY_FILES += \
    vendor/htc/marvel/proprietary/bin/akmd:/system/bin/akmd

# Touchscreen
PRODUCT_COPY_FILES += \
    vendor/htc/marvel/proprietary/usr/idc/atmel-touchscreen.idc:/system/usr/idc/atmel-touchscreen.idc \
    vendor/htc/marvel/proprietary/usr/idc/atmel-touchscreen.idc:/system/usr/idc/cy8c-touchscreen.idc

# Firmware
PRODUCT_COPY_FILES += \
    vendor/htc/marvel/proprietary/etc/firmware/bcm4329.hcd:/system/etc/firmware/bcm4329.hcd \
    vendor/htc/marvel/proprietary/etc/firmware/fw_bcm4329.bin:/system/etc/firmware/fw_bcm4329.bin \
    vendor/htc/marvel/proprietary/etc/firmware/fw_bcm4329_apsta.bin:/system/etc/firmware/fw_bcm4329_apsta.bin \
    vendor/htc/marvel/proprietary/etc/firmware/yamato_pfp.fw:/system/etc/firmware/yamato_pfp.fw \
    vendor/htc/marvel/proprietary/etc/firmware/yamato_pm4.fw:/system/etc/firmware/yamato_pm4.fw

# Config files
PRODUCT_COPY_FILES += \
    vendor/htc/marvel/proprietary/etc/AudioFilter.csv:/system/etc/AudioFilter.csv \
    vendor/htc/marvel/proprietary/etc/AudioPara4.csv:/system/etc/AudioPara4.csv \
    vendor/htc/marvel/proprietary/etc/AudioPara4_WB.csv:/system/etc/AudioPara4_WB.csv \
    vendor/htc/marvel/proprietary/etc/AudioPreProcess.csv:/system/etc/AudioPreProcess.csv \
    vendor/htc/marvel/proprietary/etc/WPDB.zip:/system/etc/WPDB.zip \
    vendor/htc/marvel/proprietary/etc/egl.cfg:/system/etc/egl.cfg
    vendor/htc/marvel/proprietary/etc/vold.fstab:/system/etc/vold.fstab

# Graphics
PRODUCT_COPY_FILES += \
    vendor/htc/marvel/proprietary/lib/egl/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
    vendor/htc/marvel/proprietary/lib/egl/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/marvel/proprietary/lib/egl/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/marvel/proprietary/lib/egl/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so

# All the blobs necessary for passion
PRODUCT_COPY_FILES += \
    vendor/htc/marvel/proprietary/lib/libaudioeq.so:/system/lib/libaudioeq.so \
    vendor/htc/marvel/proprietary/lib/libcamera.so:/system/lib/libcamera.so \
    vendor/htc/marvel/proprietary/lib/libgsl.so:/system/lib/libgsl.so \
    vendor/htc/marvel/proprietary/lib/libhtc_acoustic.so:/system/lib/libhtc_acoustic.so \
    vendor/htc/marvel/proprietary/lib/libhtc_ril.so:/system/lib/libhtc_ril.so \
    vendor/htc/marvel/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/htc/marvel/proprietary/lib/libmm-adspsvc.so:/system/lib/libmm-adspsvc.so \
    vendor/htc/marvel/proprietary/lib/liboemcamera.so:/system/lib/liboemcamera.so \
    vendor/htc/marvel/proprietary/lib/libOmxH264Dec.so:/system/lib/libOmxH264Dec.so \
    vendor/htc/marvel/proprietary/lib/libOmxMpeg4Dec.so:/system/lib/libOmxMpeg4Dec.so \
    vendor/htc/marvel/proprietary/lib/libOmxVidEnc.so:/system/lib/libOmxVidEnc.so \
    vendor/htc/marvel/proprietary/lib/libOpenVG.so:/system/lib/libOpenVG.so

